eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8802
spring:
  application:
    name: zuul-server

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: home-server
    api-b:
      path: /api-b/**
      serviceId: user-server

