eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8803
spring:
  application:
    name: home-server

#开启Hystrix的断路器功能
feign:
    hystrix:
    enabled: true